name: Gessential
description: "Note taking app with Gemini"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  speech_to_text: ^7.0.0
  google_generative_ai: ^0.2.0
  sqflite: ^2.3.2
  path: ^1.8.3
  intl: ^0.19.0
  flutter_markdown: ^0.6.20
  shared_preferences: ^2.3.3
  shadcn_ui: ^0.23.1
  google_fonts: ^6.2.1
  quick_actions: ^1.1.0
  url_launcher: ^6.3.1

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - .env
